# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

python:
   setup_py_install: false
   install:
   - requirements: docs/requirements.txt

version: 2

build:
  os: ubuntu-22.04
